[Table of contents](../toc.ipynb)

<img src="https://github.com/numpy/numpy/raw/master/doc/source/_static/numpy_logo.png" alt="Numpy" width="350" align="right">

# Numpy

* Numpy is probably the most applied and used Python package. Almost any scientific package builds on numpy.
* Numpy provides multidimensional array objects, and allows to deal with matrix computations.
* Add to this, numpy provides interfaces to C and C++.
* Numpy's methods are very efficient implemented.
* Please find numpy's documentation here [https://numpy.org/](https://numpy.org/).
* Numpy is one building block of Python's scientific eco system. If you want to know more about scientific Python, consult the scipy lecture notes on [https://scipy-lectures.org/](https://scipy-lectures.org/).

## Numpy import

First, let us import numpy, create a vector and compare this with a Python list, which ships per default with Python.

In [1]:
import numpy as np

In [10]:
a_list = range(0, 8000)
a_np_array = np.arange(0, 8000) 

Now, let us compare how long it takes to loop over the list and over the numpy array with `%timeit` magic command.

In [11]:
%timeit [i + 3 for i in a_list]

383 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
%timeit a_np_array + 3

2.69 µs ± 49.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Numpy is much faster than the list and the code of numpy is easier to read!

## Create arrays manually

* The "manual" syntax to create a numpy array is 
  * `np.array([x, x])` for one dimensional arrays 
  * and `np.array([[x, x], [x, x]])` for multidimensional arrays.
* Add to this, various functions like `np.ones()`, `np.eye()`, `np.arrange()`, `np.linspace()`, and many more create specific arrays which are often required in matrix computing.

In [22]:
# a one dimensional array
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [23]:
# here two dimesions
b = np.array([[0, 1], [2, 3]])
b

array([[0, 1],
       [2, 3]])

In [24]:
# now check their shapes
print(a.shape)
print(b.shape)

(4,)
(2, 2)


## Basic attributes

In addition to `ndarray.shape`, numpy arrays contain the attributes:
* `ndarray.ndim` which is the dimension of the array,
* `ndarray.size` which is the number of elements in the array,
* `ndarray.dtype` which is the type of the array (int16, int32, uint16, ..., the default is int64, or float64).

In [49]:
a.dtype

dtype('int64')

In [51]:
a.ndim

1

In [52]:
a.size

4

## More array constructors

### np.arange

* Create arrays with start, stop, and step size.

In [27]:
# liniear growing array, zero based
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
# np.arange with start, end, step call
np.arange(0, 12, 2)

array([ 0,  2,  4,  6,  8, 10])

### np.linspace

* Create equidistant arrays with start, stop, and number of points.

In [34]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [36]:
np.linspace(0, 10, 13)

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        ])

### Special matrices

In [37]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones(shape=(3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [43]:
np.zeros(shape=(3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Random number arrays

* Numpy's `np.random.xxx` module offers many random number generators.

In [47]:
np.random.rand(3, 3) # is uniform

array([[0.33139213, 0.76582025, 0.32026578],
       [0.61788208, 0.60622223, 0.48204055],
       [0.14504896, 0.1039804 , 0.80814987]])

In [48]:
np.random.randn(3, 3) # standard normal distribution

array([[-1.24632339,  0.55116507, -0.98204727],
       [-0.09720894,  0.5698674 , -0.48410166],
       [ 1.30412975, -1.24582235, -0.54471462]])